[[plugins]]

  package = "netlify-plugin-flutter"

   [plugins.inputs]
    channel = "stable"

[build]

command = "flutter build web --no-tree-shake-icons --web-renderer html --release"
publish = "build/web"